const populate = async (value, currency) => {
  let mystr = "";
  url = "https://api.currencyapi.com/v3/latest?apikey=cur_live_QCoGhx1lGNyVSEBkO8i2jS1FchgXlbCmgDPMkkw1&base_currency=" + currency;

  let response = await fetch(url);
  let result = await response.json();

  document.querySelector(".output").style.display = "block";

  for (let key of Object.keys(result["data"])) {
    let num = (result["data"][key]["value"] * value).toFixed(3);
    if (currency != key) {
      mystr += `
    <tr>   
        <td>${key}</td>        
        <td>${result["data"][key]["code"]}</td>        
        <td>${num}</td>
    </tr>        
        `
    }
  }
  const tablebody = document.querySelector("tbody");
  tablebody.innerHTML = mystr;
}

const button = document.querySelector(".btn");
button.addEventListener("click", (e) => {
  e.preventDefault();
  const value = parseInt(document.querySelector("input[name='quantity']").value);
  const currency = document.querySelector("select[name='currency']").value;
  populate(value, currency);
})

// Currency Names with respective Codes
// DAI,OP,SOL,STD,USDC,XAG,XAU,XPD,XPT,XRP,ZMK and ZML are not in the following Object.... 
// let namecodes = {
//   AED: "UAE Dirham",
//   ADA: "Cardano",
//   AFN: "Afghani",
//   ALL: "Albania Lek",
//   AMD: "Armenia Dram",
//   ANG: "Antilles Guilder",
//   AOA: "Angola Kwanza",
//   ARB: "Arbitrum",
//   ARS: "Argentina Peso",
//   AUD: "Australia Dollar",
//   AVAX: "Avalanche",
//   AWG: "Aruba Guilder",
//   AZN: "Azerbaijan Manat",
//   BAM: "Mark",
//   BBD: "Barbados Dollar",
//   BDT: "Bangladesh Taka",
//   BGN: "Bulgaria Lev",
//   BHD: "Bahrain Dinar",
//   BIF: "Burundi Franc",
//   BMD: "Bermuda Dollar",
//   BND: "Brunei Darussalam Dollar",
//   BOB: "Bolivia Bolíviano",
//   BRL: "Brazil Real",
//   BSD: "Bahamas Dollar",
//   BTC: "Bitcoin",
//   BTN: "Bhutan Ngultrum",
//   BUSD: "Binance USD",
//   BWP: "Botswana Pula",
//   BYN: "Belarus Ruble",
//   BYR: "Bhayandar",
//   BZD: "Belize Dollar",
//   CAD: "Canada Dollar",
//   CDF: "Congo Franc",
//   CHF: "Switzerland Franc",
//   CLF: "Chilean Unit of Account",
//   CLP: "Chile Peso",
//   CNY: "China Yuan",
//   COP: "Colombia Peso",
//   CRC: "Costa Rica Colon",
//   CUC: "Cuba Convertible Peso",
//   CUP: "Cuba Peso",
//   CVE: "Cape Verde Escudo",
//   CZK: "Czech Republic Koruna",
//   DJF: "Djibouti Franc",
//   DKK: "Denmark Krone",
//   DOP: "Dominican Peso",
//   DOT: "Polkadot USD",
//   DZD: "Algeria Dinar",
//   EGP: "Egypt Pound",
//   ERN: "Eritrea Nakfa",
//   ETB: "Ethiopia Birr",
//   ETH: "Ethereum",
//   EUR: "Euro",
//   FJD: "Fiji Dollar",
//   FKP: "Falkland Islands Pound",
//   GBP: "UK Pound",
//   GEL: "Georgia Lari",
//   GGP: "Guernsey Pound",
//   GHS: "Ghana Cedi",
//   GIP: "Gibraltar Pound",
//   GMD: "Gambia Dalasi",
//   GNF: "Guinea Franc",
//   GTQ: "Guatemala Quetzal",
//   GYD: "Guyana Dollar",
//   HKD: "Hong Kong Dollar",
//   HNL: "Honduras Lempira",
//   HRK: "Croatia Kuna",
//   HTG: "Haiti Gourde",
//   HUF: "Hungary Forint",
//   IDR: "Indonesia Rupiah",
//   ILS: "Israel Shekel",
//   IMP: "Isle of Man Pound",
//   INR: "Indian Rupee",
//   IQD: "Iraq Dinar",
//   IRR: "Iran Rial",
//   ISK: "Iceland Krona",
//   JEP: "Jersey Pound",
//   JMD: "Jamaica Dollar",
//   JOD: "Jordan Dinar",
//   JPY: "Japan Yen",
//   KES: "Kenya Shilling",
//   KGS: "Kyrgyzstan Som",
//   KHR: "Cambodia Riel",
//   KMF: "Comorian Franc",
//   KPW: "North Korea Won",
//   KRW: "South Korea Won",
//   KWD: "Kuwait Dinar",
//   KYD: "Cayman Islands Dollar",
//   KZT: "Kazakhstan Tenge",
//   LAK: "Laos Kip",
//   LBP: "Lebanon Pound",
//   LKR: "Sri Lanka Rupee",
//   LRD: "Liberia Dollar",
//   LSL: "Lesotho Loti",
//   LTC: "Litecoin",
//   LTL: "Lithuanian litas",
//   LVL: "Latvian lats",
//   LYD: "Libya Dinar",
//   MAD: "Morocco Dirham",
//   MATIC: "Polygon",
//   MDL: "Moldova Leu",
//   MGA: "Madagascar Ariary",
//   MKD: "Macedonia Denar",
//   MMK: "Myanmar Kyat",
//   MNT: "Mongolia Tughrik",
//   MOP: "Macau Pataca",
//   MRO: "Mauritanian ouguiya",
//   MUR: "Mauritius Rupee",
//   MVR: "Maldives Rufiyaa",
//   MWK: "Malawi Kwacha",
//   MXN: "Mexico Peso",
//   MYR: "Malaysia Ringgit",
//   MZN: "Mozambique Metical",
//   NAD: "Namibia Dollar",
//   NGN: "Nigeria Naira",
//   NIO: "Nicaragua Cordoba",
//   NOK: "Norway Krone",
//   NPR: "Nepal Rupee",
//   NZD: "New Zealand Dollar",
//   OMR: "Oman Rial",
//   PAB: "Panama Balboa",
//   PEN: "Peru Sol",
//   PGK: "Papua New Guinea Kina",
//   PHP: "Philippines Peso",
//   PKR: "Pakistan Rupee",
//   PLN: "Poland Zloty",
//   PYG: "Paraguay Guarani",
//   QAR: "Qatar Riyal",
//   RON: "Romania Leu",
//   RSD: "Serbia Dinar",
//   RUB: "Russia Ruble",
//   RWF: "Rwanda Franc",
//   SAR: "Saudi Arabia Riyal",
//   SBD: "Solomon Islands Dollar",
//   SCR: "Seychelles Rupee",
//   SDG: "Sudan Pound",
//   SEK: "Sweden Krona",
//   SGD: "Singapore Dollar",
//   SHP: "Saint Helena Pound",
//   SLL: "Sierra Leone Leone",
//   SOS: "Somalia Shilling",
//   SRD: "Suriname Dollar",
//   SRD: "Suriname Dollar",
//   SRD: "Suriname Dollar",
//   SRD: "Suriname Dollar",
//   SRD: "Suriname Dollar",
//   SVC: "El Salvador Colon",
//   SYP: "Syria Pound",
//   SZL: "Swatini Lilangeni",
//   THB: "Thailand Baht",
//   TJS: "Tajikistan Somoni",
//   TMT: "Turkmenistan Manat",
//   TND: "Tunisia Dinar",
//   TOP: "Tonga Pa'anga",
//   TRY: "Turkey Lira",
//   TTD: "Trinidad & Tobago Dollar",
//   TWD: "Taiwan New Dollar",
//   TZS: "Tanzania Shilling",
//   UAH: "Ukraine Hryvnia",
//   UGX: "Uganda Shilling",
//   USD: "United States Dollar",
//   UYU: "Uruguay Peso",
//   UZS: "Uzbekistan Som",
//   VEF: "Venezuela Bolívar",
//   VND: "Viet Nam Dong",
//   VUV: "Vanuatu Vatu",
//   WST: "Samoa Tala",
//   XAF: "CFA Franc BEAC",
//   XCD: "East Caribbean Dollar",
//   XDR: "IMF Special Drawing Rights",
//   XOF: "CFA Franc",
//   XPF: "CFP Franc",
//   YER: "Yemen Rial",
//   ZAR: "South Africa Rand",
//   ZMW: "Zambia Kwacha"
// };
